### ISSUE TITLE
Hero section is overlapping the sidebar

### ISSUE THREAD

**Issue by soumyaranjanjena123** [safak/animated-portfolio#22]
After settle-up the hero component when i clicked the sidebar menu then , the sidebar is getting overlapped by the hero section. any one help me with that
![Screenshot 2023-12-04 001240](https://github.com/safak/animated-portfolio/assets/80942825/af53f280-a9b0-49e7-83fa-9cc99b7888da)

**Comment by D-singh121** [comment]
just increase z-index for  sidebar bg  to the higher (eg. 999 or 1111)

**Comment by ATHARVA262005** [comment]
in sidebar for bg and for button use z-index 999 or higher
`
.sidebar{
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    background-color: white;
    color: black;
    
    .bg{
        z-index: 999;
        position: fixed;
        top: 0;
        left: 0;
        bottom: 0;
        width: 400px;
        background-color: white;

        .links{
            position: absolute;
            height: 100%;
            width: 100%;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content:center;
            gap: 20px;

            a{
                font-size: 40px;
            }
        }
    }

    button{
        z-index: 999;
        position: fixed;
        width: 50px;
        height: 50px;
        border-radius: 50%;
        top: 25px;
        left: 25px;
        background-color: transparent;
        border: none;
        cursor: pointer;
        
    }
}
`

**Comment by soumyaranjanjena123** [comment]
thanks broo
